### ISSUE TITLE
Not sure about symlink

### ISSUE THREAD

**Issue by nitedani** [remorses/vite-plugin-nft#1]
https://github.com/remorses/vite-plugin-nft/blob/975d3089f47b73dc5224cc690ca3bfc240eca222/src/analyze.ts#L97

I think the `standalone` output folder will not be portable because of symlinks(pnpm). Try to move it to a different location/machine after build, and the symlinks will break.

Also, not sure if docker copies the real files behind symlinks, is the following really working?
`COPY ./standalone /app/standalone`

In `vite-plugin-standalone` I'm resolving all of the symlinks and instead create a flat `node_modules` in the output folder. This makes the folder truly portable.

I use esbuild before the nft step for tree-shaking the imports. With nft you copy whole files, making the output folder larger.
So I use nft only for files that can't be bundled by esbuild (binaries, etc..). The build environment architecture needs to match the runtime for it to work though.

**Comment by remorses** [comment]
Hi, thank you for vite-plugin-standalon, this project started as a fork but then it diverged enough to create a new package

1. symplinks will work correctly, i copied the same code from Next.js (which i helped write too), the symplinks will be all relative to the base, this works if symplinks don't get outside of it, which is the case. I am already using this project with a pnpm monorepo and it works ok and is portable
2. I don't think hoisting node_modules is a good idea because a dependency could be a different version based on which folder it is inside
3. I removed esbuild because it is unnecessary in my opinion, Rollup should be already be removing imports of unused stuff, I also wanted to copy exactly what Next.js does because i know it already works in production well

**Comment by remorses** [comment]
But i found a better way, stop using esm

I started using this approach of standalone because vite does not support commonjs dependencies in noExternal, it will leave require even if you are inside a type: module package.

This plugin would make it possible to leave the commonjs dependencies external so they work correctly but the better way is to just bundle everything into a commonjs file with native dependencies externalized (this breaks if native dep is esm only tho)

So i decided to switch to commonjs and everything works, Vite is a bitch tbh

```ts
import { vitePlugin as remix } from '@remix-run/dev'
import { defineConfig } from 'vite'

const building = !!process.env.BUILDING

export default defineConfig({
    plugins: [
        remix({
            appDirectory: 'src',
            serverModuleFormat: 'cjs',
        }),
    ],

    ssr: {
        noExternal: building || undefined,
        external: ['@prisma/client', 'native-dep'],
    },
    legacy: {
        proxySsrExternalModules: true,
    },
})

```

**Comment by nitedani** [comment]
> 3\. Rollup should be already be removing imports of unused stuff

You're right, if the module is `noExtenal` it does, but it gets slow as the project grows. I opted to use esbuild instead because it's also shipped with vite and much faster than rollup. I want to remove the esbuild step after vite migrates to rolldown and everything will be `noExternal` by default. Esbuild leaves "require" in the code too :( Had to add a hacky banner to every output file..


> 2\. I don't think hoisting node_modules is a good idea because a dependency could be a different version based on which folder it is inside

Yes, it's an issue with my version :( But symlinks can have issues too when zipping/unzipping the standalone folder for example. I wanted to avoid such issues. I think both ways have their drawbacks and don't know what to do about it. Maybe symlinks are better after all.

> it will leave require even if you are inside a type: module package.

Maybe you can add this banner to the output files and keep "esm", what do you think?

```
import { dirname as dirname987 } from 'path';
import { fileURLToPath as fileURLToPath987 } from 'url';
import { createRequire as createRequire987 } from 'module';
var require = createRequire987(import.meta.url);
var __filename = fileURLToPath987(import.meta.url);
var __dirname = dirname987(__filename);
```

**Comment by remorses** [comment]
Thank you for the idea of adding require at the top, maybe that would work too. But using commonjs as the output is the best way in my opinion so I don’t have to mess with build options. The only thing I lose is top level await
